name: Build and Publish Package

on:
  push:
    tags:
      - "*"
    branches:
      - "master"

jobs:
  build_wheel:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Download UV
        uses: astral-sh/setup-uv@v5

      - name: Build Package
        run: uvx cibuildwheel

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ strategy.job-index }}
          path: ${{ github.workspace }}/wheelhouse/*.whl

  build_source:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download UV
        uses: astral-sh/setup-uv@v5

      - name: Build Source
        run: uv build --sdist

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-sdist
          path: dist/*.tar.gz
          
  publish:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [ build_wheel, build_source ]
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download from GitHub
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: ${{ github.workspace }}/dist
          merge-multiple: true
          
      - name: Download UV
        uses: astral-sh/setup-uv@v5

      - name: Publish to PyPi
        run: uv publish

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/dist/*
